import { useState, useCallback } from "react";
import { ERCData, categoryColors } from "@/data/ercData";
import { Badge } from "@/components/ui/badge";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Layers, X, Download, Copy, Check, Plus, Trash2 } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
interface StackBuilderProps {
  stack: ERCData[];
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onRemove: (number: string) => void;
  onClear: () => void;
}

// ---------------------------------------------------------------------------
// Export helpers
// ---------------------------------------------------------------------------
function generateMarkdown(stack: ERCData[]): string {
  const lines: string[] = [
    "# My ERC Stack",
    "",
    `> Generated by [ercWhat](https://ercwhat.app) — ${new Date().toLocaleDateString()}`,
    "",
    "## Standards",
    "",
  ];

  for (const erc of stack) {
    lines.push(`### ERC-${erc.number} — ${erc.title}`);
    lines.push("");
    lines.push(`**Category:** ${erc.category}`);
    lines.push("");
    lines.push(erc.summary);
    lines.push("");
    lines.push("**Key Features:**");
    for (const f of erc.keyFeatures) lines.push(`- ${f}`);
    lines.push("");
    lines.push("**Use Cases:**");
    for (const uc of erc.useCases) lines.push(`- ${uc}`);
    lines.push("");
    lines.push(`**EIP:** https://eips.ethereum.org/EIPS/eip-${erc.number}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  if (stack.some((e) => e.relatedERCs?.length)) {
    lines.push("## Pairings");
    lines.push("");
    for (const erc of stack) {
      if (erc.relatedERCs?.length) {
        lines.push(
          `- **ERC-${erc.number}** pairs well with: ${erc.relatedERCs.map((r) => `ERC-${r}`).join(", ")}`
        );
      }
    }
    lines.push("");
  }

  return lines.join("\n");
}

function generateJson(stack: ERCData[]): string {
  return JSON.stringify(
    {
      generated: new Date().toISOString(),
      tool: "ercWhat",
      stack: stack.map((erc) => ({
        number: erc.number,
        title: erc.title,
        category: erc.category,
        status: erc.status,
        eip: `https://eips.ethereum.org/EIPS/eip-${erc.number}`,
        keyFeatures: erc.keyFeatures,
        useCases: erc.useCases,
        relatedERCs: erc.relatedERCs ?? [],
      })),
    },
    null,
    2
  );
}

function downloadFile(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ---------------------------------------------------------------------------
// FloatingBar — shown in Index when stack has items
// ---------------------------------------------------------------------------
export const StackBar = ({
  count,
  onOpen,
  onClear,
}: {
  count: number;
  onOpen: () => void;
  onClear: () => void;
}) => (
  <AnimatePresence>
    {count > 0 && (
      <motion.div
        initial={{ y: 100, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        exit={{ y: 100, opacity: 0 }}
        transition={{ type: "spring", stiffness: 300, damping: 30 }}
        className="fixed bottom-20 left-1/2 z-50 -translate-x-1/2"
      >
        <div className="flex items-center gap-3 rounded-full border border-border bg-card px-5 py-2.5 shadow-lg shadow-background/50">
          <Layers className="h-4 w-4 text-primary" />
          <span className="text-sm text-muted-foreground">
            <span className="font-mono font-bold text-primary">{count}</span> in stack
          </span>
          <button
            onClick={onOpen}
            className="rounded-full bg-primary px-4 py-1.5 text-xs font-semibold text-primary-foreground transition-colors hover:bg-primary/90"
          >
            View Stack
          </button>
          <button
            onClick={onClear}
            className="rounded-full bg-secondary px-3 py-1.5 text-xs text-muted-foreground transition-colors hover:text-foreground"
          >
            Clear
          </button>
        </div>
      </motion.div>
    )}
  </AnimatePresence>
);

// ---------------------------------------------------------------------------
// Main drawer
// ---------------------------------------------------------------------------
const StackBuilder = ({ stack, open, onOpenChange, onRemove, onClear }: StackBuilderProps) => {
  const [copied, setCopied] = useState(false);
  const [exportFmt, setExportFmt] = useState<"markdown" | "json">("markdown");

  const handleCopyMarkdown = useCallback(() => {
    navigator.clipboard.writeText(generateMarkdown(stack));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast.success("Stack copied to clipboard!");
  }, [stack]);

  const handleDownload = useCallback(() => {
    if (exportFmt === "markdown") {
      downloadFile(generateMarkdown(stack), "my-erc-stack.md", "text/markdown");
    } else {
      downloadFile(generateJson(stack), "my-erc-stack.json", "application/json");
    }
    toast.success(`Downloaded as ${exportFmt === "markdown" ? ".md" : ".json"}`);
  }, [stack, exportFmt]);

  if (stack.length === 0 && !open) return null;

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full max-w-md border-border bg-card overflow-y-auto">
        <SheetHeader className="mb-4">
          <div className="flex items-center justify-between">
            <SheetTitle className="flex items-center gap-2 text-foreground">
              <Layers className="h-5 w-5 text-primary" />
              Stack Builder
            </SheetTitle>
            {stack.length > 0 && (
              <button
                onClick={onClear}
                className="flex items-center gap-1 rounded-md border border-border px-2.5 py-1 text-xs text-muted-foreground transition-colors hover:border-destructive/50 hover:text-destructive"
              >
                <Trash2 className="h-3 w-3" /> Clear all
              </button>
            )}
          </div>
          <p className="text-xs text-muted-foreground">
            Pin ERCs using the <Plus className="inline h-3 w-3" /> button on any card, then export your architecture.
          </p>
        </SheetHeader>

        {stack.length === 0 ? (
          <div className="flex flex-col items-center justify-center gap-3 py-20 text-center">
            <div className="rounded-full bg-secondary p-4">
              <Layers className="h-8 w-8 text-muted-foreground" />
            </div>
            <p className="text-sm font-medium text-foreground">Your stack is empty</p>
            <p className="max-w-xs text-xs text-muted-foreground">
              Add ERCs to your stack by clicking the bookmark icon on any ERC card.
            </p>
          </div>
        ) : (
          <>
            {/* Stack list */}
            <div className="space-y-2 mb-6">
              <AnimatePresence>
                {stack.map((erc, i) => (
                  <motion.div
                    key={erc.number}
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 20 }}
                    transition={{ delay: i * 0.04 }}
                    className="flex items-start gap-3 rounded-lg border border-border bg-secondary/30 p-3"
                  >
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="font-mono text-sm font-bold text-primary">ERC-{erc.number}</span>
                        <span className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${categoryColors[erc.category]}`}>
                          {erc.category}
                        </span>
                      </div>
                      <p className="text-sm font-medium text-foreground">{erc.title}</p>
                      <p className="mt-0.5 text-xs text-muted-foreground line-clamp-2">{erc.summary}</p>
                      <div className="mt-2 flex flex-wrap gap-1">
                        {erc.keyFeatures.slice(0, 3).map((f) => (
                          <Badge key={f} variant="secondary" className="text-[10px]">{f}</Badge>
                        ))}
                      </div>
                    </div>
                    <button
                      onClick={() => onRemove(erc.number)}
                      className="shrink-0 rounded-full p-1 text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
                    >
                      <X className="h-4 w-4" />
                    </button>
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>

            {/* Pairing suggestions */}
            {(() => {
              const stackNumbers = stack.map((e) => e.number);
              const suggestions = new Set<string>();
              stack.forEach((erc) => {
                erc.relatedERCs?.forEach((r) => {
                  if (!stackNumbers.includes(r)) suggestions.add(r);
                });
              });
              if (!suggestions.size) return null;
              return (
                <div className="mb-6 rounded-lg border border-border bg-background p-3">
                  <p className="mb-2 text-xs font-semibold text-foreground">Suggested additions</p>
                  <div className="flex flex-wrap gap-1.5">
                    {[...suggestions].map((r) => (
                      <Badge key={r} variant="outline" className="font-mono text-xs text-primary">
                        ERC-{r}
                      </Badge>
                    ))}
                  </div>
                </div>
              );
            })()}

            {/* Export section */}
            <div className="rounded-lg border border-border bg-background p-4 space-y-3">
              <p className="text-xs font-semibold text-foreground">Export your stack</p>

              {/* Format toggle */}
              <div className="flex gap-1 rounded-md border border-border bg-card p-1">
                {(["markdown", "json"] as const).map((fmt) => (
                  <button
                    key={fmt}
                    onClick={() => setExportFmt(fmt)}
                    className={`flex-1 rounded py-1.5 text-xs font-medium transition-all ${
                      exportFmt === fmt
                        ? "bg-primary text-primary-foreground"
                        : "text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    .{fmt === "markdown" ? "md" : "json"}
                  </button>
                ))}
              </div>

              <div className="flex gap-2">
                <button
                  onClick={handleDownload}
                  className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground transition-colors hover:bg-primary/90"
                >
                  <Download className="h-3.5 w-3.5" />
                  Download
                </button>
                <button
                  onClick={handleCopyMarkdown}
                  className="flex items-center gap-2 rounded-lg border border-border bg-secondary px-4 py-2.5 text-xs text-muted-foreground transition-colors hover:text-foreground"
                >
                  {copied ? <Check className="h-3.5 w-3.5 text-green-400" /> : <Copy className="h-3.5 w-3.5" />}
                  {copied ? "Copied!" : "Copy"}
                </button>
              </div>
            </div>
          </>
        )}
      </SheetContent>
    </Sheet>
  );
};

export default StackBuilder;